- name: Web Server Configuration
  hosts: all
  tasks:
   - name: Installing HTTPD PACKAGE
     package: 
       name: "httpd"
       state: "present"
   - name: Adding Website Files 
     copy:
       src: "index.php"
       dest: "/var/www/html"
   - name: Starting HTTPD Service
     service:
       name: "httpd"
       state: "started"
